# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.cache:
    class: Trimm\Jelastic\Service\Cache
  app.api:
    class: Trimm\Jelastic\Service\Api
    arguments: ['@app.cache']
  app.deployer:
    class: Trimm\Jelastic\Service\Deployer
    arguments: ['@app.projectConfig', '@app.api']
  app.projectConfig:
    class: Trimm\Jelastic\Service\ProjectConfig
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
